'section: tests':
  - changed-files:
      - any-glob-to-any-file:
          - '**/__tests__/**'
          - 'jest.config.ts'

'section: workflows':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'

'section: repo':
  - changed-files:
      - any-glob-to-any-file:
          - '**'

'experience: developer':
  - changed-files:
      - any-glob-to-any-file:
          - '.eslintignore'
          - '.eslintrc.json'
          - '.gitignore'
          - '.npmrc'
          - '.prettierrc'
          - 'tslint.json'
          - '.stylintrc'
          - '.postcssrc.cjs'
          - '.postcssrc.js'

'context: github':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

'context: docker':
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile'

'context: npm':
  - changed-files:
      - any-glob-to-any-file:
          - '.npmrc'

'context: rollup':
  - changed-files:
      - any-glob-to-any-file:
          - 'rollup.config.js'
          - 'rollup.*.config.js'

'mindless: docs':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'

'mindless: 📦 dependencies':
  - changed-files:
      - any-glob-to-any-file:
          - 'package-lock.json'
